version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Web-UI for Redis: https://redis.io/insight/
  # Überblick weitere Redis-UIs: https://uibakery.io/blog/redis-gui-tools
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
